title: Nirali Bhansali
logo: assets/img/R.jpeg
description: 
I have completed M.sc in clinical Psychology. I'm here to upgrade my skills.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
